### 元素相乘
该操作又称作 "哈达玛积", 简单来说就是 tensor 元素逐个相乘。这个操作，是通过 * 也就是常规的乘号操作符定义的操作结果。torch.mul 是等价的。

In [1]:
import torch

# mul 和 * 一致，按照元素位置进行相乘，不做降维
def element_by_element():
    
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([4, 5, 6])
    
    return x * y, torch.mul(x, y)

element_by_element()

(tensor([ 4, 10, 18]), tensor([ 4, 10, 18]))

In [ ]:
# 向量和标量相乘，会进行broadcast进行广播
def element_by_element_broadcast():
    
    x = torch.tensor([1, 2, 3])
    y = 2
    
    return x * y

element_by_element_broadcast()

### 向量点乘
torch.matmul: If both tensors are 1-dimensional, the dot product (scalar) is returned.
如果都是1维的，返回的就是 dot product 结果


In [3]:
# 向量matmul 点积按照维度相乘之后再相加，会进行降维处理
def vec_dot_product():
    
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([4, 5, 6])
    
    return torch.matmul(x, y)
vec_dot_product()
# tensor(32)

tensor(32)

### 矩阵乘法
torch.matmul: If both arguments are 2-dimensional, the matrix-matrix product is returned.
<BR/>如果都是2维，那么就是矩阵乘法的结果返回。与 torch.mm 是等价的，torch.mm 仅仅能处理的是矩阵乘法。

In [4]:
def matrix_multiple():
    
    x = torch.tensor([
        [1, 2, 3],
        [4, 5, 6]
    ])
    y = torch.tensor([
        [7, 8],
        [9, 10],
        [11, 12]
    ])
    
    return torch.matmul(x, y), torch.mm(x, y)

matrix_multiple()

(tensor([[ 58,  64],
         [139, 154]]),
 tensor([[ 58,  64],
         [139, 154]]))

### vector 与 matrix 相乘
torch.matmul: If the first argument is 1-dimensional and the second argument is 2-dimensional, a 1 is prepended to its dimension for the purpose of the matrix multiply. After the matrix multiply, the prepended dimension is removed.

如果第一个是 vector, 第二个是 matrix, 会在 vector 中增加一个维度。也就是 vector 变成了  与 matrix  相乘之后，变成 , 在结果中将  维 再去掉。


In [5]:
def vec_matrix():
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([
        [7, 8],
        [9, 10],
        [11, 12]
    ])
    
    return torch.matmul(x, y)

vec_matrix()

tensor([58, 64])

### matrix 与 vector 相乘
同样的道理， vector会被扩充一个维度。

In [6]:
def matrix_vec():
    x = torch.tensor([
        [1, 2, 3],
        [4, 5, 6]
    ])
    y = torch.tensor([
        7, 8, 9
    ])
    
    return torch.matmul(x, y)

matrix_vec()

tensor([ 50, 122])