### 元素相乘
该操作又称作 "哈达玛积", 简单来说就是 tensor 元素逐个相乘。这个操作，是通过 * 也就是常规的乘号操作符定义的操作结果。torch.mul 是等价的。

In [2]:
import torch

# 元素相乘，不是点乘
def element_by_element():
    
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([4, 5, 6])
    
    return x * y, torch.mul(x, y)

print (element_by_element())

(tensor([ 4, 10, 18]), tensor([ 4, 10, 18]))


### 向量点乘
向量相乘 每个元素按照列相乘之后再统一相加
x(i) * y(i) + x(i+1) * y(i+1)

In [8]:
import random
import torch

# 元素点乘：向量 * 向量  = 标量
def vec_dot_product():
    
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([4, 5, 6])
    
    return torch.matmul(x, y)
# vec_dot_product()

# 点乘：矩阵 * 向量
def vec_dot_product1():
    
    x = torch.Tensor([2.,2.])
    print(x)
    y = torch.arange(0,10.0,1).reshape(2,5)
    # print(x.transpose(0,1))
    # a = torch.normal(0,1,(5,2))
    # a = torch.arange(0,1,0.1).reshape(5,2)
    print(y)
    return torch.matmul(y,x)

# 向量和矩阵相乘，矩阵进行转置之后进行mul
print(vec_dot_product1())



# a = torch.arange(0,10.0,1).reshape(5,2)
# print(a)

# b = torch.arange(0,10.0,1).reshape(2,5)
# print(b)

# print(torch.matmul(a,b))



tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
tensor([2., 2.])
tensor([10., 14., 18., 22., 26.])


### 一、点乘
点乘都是broadcast的，可以用torch.mul(a, b)实现，也可以直接用*实现。
</BR>注意：广播是补全缺失的列，但是维度必须相同
例如：一个二维矩阵，必须和一个二维相乘，两个的列可以不同，系统会自动广播补充

In [ ]:
import random
import torch

a = torch.ones(3,4)
b = torch.Tensor([1,2,3]).reshape((3,1))
print(b)
torch.mul(a, b)

### 矩阵乘法

如果是二维数组（矩阵）之间的运算，则得到的是矩阵积（mastrix product）。
所得到的数组中的每个元素为，第一个矩阵中与该元素行号相同的元素与第二个矩阵与该元素列号相同的元素，两两相乘后再求和。
这句话有点难理解，但是这句话里面没有哪个字是多余的。结合下图理解这句话。
<BR>
mm 只能使用在二维矩阵 matmul可以使用多为矩阵相乘

![avatar](numpy.dot.png)
<br/>
解释：
    x = torch.tensor([
        [1, 1, 1],
        [1, 1, 1]
    ])
    y = torch.tensor([
        [2, 2],
        [2, 2],
        [2, 3]
    ])
<br/>
x 先使用第1行和 y 的第1列相乘，得到新matrix [Update,0][0,0]数据，和y相乘的列决定了当前列的位置，即为0 
<br/>
x 先使用第1行和 y 的第2列相乘，得到新matrix [0,Update][0,0]数据，和y相乘的列决定了当前列的位置，即为1
<br/>
之后一次类推；所有两个矩阵相乘需要确认[a,b][c,d] b=c 是否相等


In [ ]:
# 关于矩阵乘法的Sample
# 如果都是2维，那么就是矩阵乘法的结果返回。与 torch.mm 是等价的，torch.mm 仅仅能处理的是矩阵乘法。

# numpy.dot() 对于两个一维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为内积)；
# 对于二维数组，计算的是两个数组的矩阵乘积；对于多维数组，
# 它的通用计算公式如下，即结果数组中的每个元素都是：
# 数组a的最后一维上的所有元素与数组b的倒数第二位上的所有元素的乘积和： dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])。
import random
import torch

def matrix_multiple():
    
    x = torch.tensor([
        [1, 1, 1],
        [1, 1, 1]
    ])
    y = torch.tensor([
        [2, 2],
        [2, 2],
        [2, 3]
    ])
    # print(y.transpose(0,1))
    
    return torch.matmul(x, y), torch.mm(x, y)

print(matrix_multiple())