### 元素相乘
该操作又称作 "哈达玛积", 简单来说就是 tensor 元素逐个相乘。这个操作，是通过 * 也就是常规的乘号操作符定义的操作结果。torch.mul 是等价的。
<br/>元素相乘是不降维度的


In [34]:
import torch
# 元素相乘，不做点积处理，直接元素对位进行相乘；
# mul 和 * 运算方式一致；

def element_by_element():
    
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([4, 5, 6])    
    return x * y, torch.mul(x, y)

print(element_by_element())
# (tensor([ 4, 10, 18]), tensor([ 4, 10, 18]))

# 这个操作是可以 broad cast 的。
def element_by_element_broadcast():
    x = torch.tensor([1, 2, 3])
    y = 2
    return x * y

element_by_element_broadcast()

(tensor([ 4, 10, 18]), tensor([ 4, 10, 18]))


### 向量点乘
向量相乘 每个元素按照列相乘之后再统一相加
x(i) * y(i) + x(i+1) * y(i+1)

In [37]:
import torch

# 如果都是1维的，返回的就是 dot product 结果
# 向量 *  向量 = 标量
# 矩阵 * 向量 = 矩阵
# 矩阵 *  矩阵 = 矩阵

def vec_dot_product():
    
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([4, 5, 6])
    
    # 不能将matmul改为mm mm只能处理矩阵乘法
    return torch.matmul(x, y)
vec_dot_product()
# tensor(32)

tensor(32)

### 矩阵乘法(M,N) * (N,L)
如果都是2维，那么就是矩阵乘法的结果返回。与 torch.mm 是等价的，torch.mm 仅仅能处理的是矩阵乘法。

In [41]:
import torch
def matrix_multiple():
    
    x = torch.tensor([
        [1, 2, 3],
        [4, 5, 6]
    ])
    y = torch.tensor([
        [7, 8],
        [9, 10],
        [11, 12]
    ])
    
    return torch.matmul(x, y), torch.mm(x, y)

matrix_multiple()

(tensor([[ 58,  64],
         [139, 154]]),
 tensor([[ 58,  64],
         [139, 154]]))

## vector 与 matrix 相乘
如果第一个是 vector, 第二个是 matrix, 会在 vector 中增加一个维度。也就是 vector 变成了 shape: (1 \times N) 与 matrix (N \times M) 相乘之后，变成 (1 \times M), 在结果中将 1 维 再去掉。

In [58]:
import torch

# vector 与 matrix 相乘
# Vector[N] 变成 1*N, (1*N) * (N*M) 确认N = N，不然不能进行计算
# matmul 有计算方向，如果将x * y 改变程 y * x 则违反上面的定义N=N，不能进行计算；s

# (1,3) * (3,2) = (1,2)
def vec_matrix():
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([
        [7, 8],
        [9, 10],
        [11, 12]
    ])
    
    return torch.matmul(x,y)

vec_matrix()
# tensor([58, 64])

tensor([58, 64])

### matrix 与 vector 相乘
同样的道理， vector会被扩充一个维度。

In [59]:
def matrix_vec():
    x = torch.tensor([
        [1, 2, 3],
        [4, 5, 6]
    ])
    y = torch.tensor([
        7, 8, 9
    ])
    
    return torch.matmul(x, y)

matrix_vec()

tensor([ 50, 122])

In [24]:
import random
import torch

# 元素点乘：向量 * 向量  = 标量
def vec_dot_product():
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([4, 5, 6])
    return torch.matmul(x, y)
# vec_dot_product()

# 点乘：vector 与 matrix 相乘
# Vector[N] 变成 1*N, (1*N) * (N*M) 确认N = N，不然不能进行计算
# matmul 有计算方向，如果将x * y 改变程 y * x 则违反上面的定义N=N，不能进行计算；s
def vec_dot_matrix():
    x = torch.Tensor([2.,2.])
    print(x)
    y = torch.arange(0,6.0,1).reshape(2,3)
    print(y)
    # print(x.transpose(0,1))
    # a = torch.normal(0,1,(5,2))
    # a = torch.arange(0,1,0.1).reshape(5,2)
    return torch.matmul(x,y)
# 向量和矩阵相乘，矩阵进行转置之后进行mul
print(vec_dot_matrix())

# matrix 与 vector 相乘
def matrix_dot_vec():
    x = torch.tensor([
        [1, 2, 3],
        [4, 5, 6]
    ])
    y = torch.tensor([
        7, 8, 9
    ])
    
    return torch.matmul(x, y)

# print(matrix_dot_vec())

# a = torch.arange(0,10.0,1).reshape(5,2)
# print(a)

# b = torch.arange(0,10.0,1).reshape(2,5)
# print(b)

# print(torch.matmul(a,b))



tensor([2., 2.])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([ 6., 10., 14.])


### 一、点乘
点乘都是broadcast的，可以用torch.mul(a, b)实现，也可以直接用*实现。
</BR>注意：广播是补全缺失的列，但是维度必须相同
例如：一个二维矩阵，必须和一个二维相乘，两个的列可以不同，系统会自动广播补充

In [ ]:
import random
import torch

a = torch.ones(3,4)
b = torch.Tensor([1,2,3]).reshape((3,1))
print(b)
torch.mul(a, b)

### 矩阵乘法

如果是二维数组（矩阵）之间的运算，则得到的是矩阵积（mastrix product）。
所得到的数组中的每个元素为，第一个矩阵中与该元素行号相同的元素与第二个矩阵与该元素列号相同的元素，两两相乘后再求和。
这句话有点难理解，但是这句话里面没有哪个字是多余的。结合下图理解这句话。
<BR>
mm 只能使用在二维矩阵 matmul可以使用多为矩阵相乘

![avatar](numpy.dot.png)
<br/>
解释：
    x = torch.tensor([
        [1, 1, 1],
        [1, 1, 1]
    ])
    y = torch.tensor([
        [2, 2],
        [2, 2],
        [2, 3]
    ])
<br/>
x 先使用第1行和 y 的第1列相乘，得到新matrix [Update,0][0,0]数据，和y相乘的列决定了当前列的位置，即为0 
<br/>
x 先使用第1行和 y 的第2列相乘，得到新matrix [0,Update][0,0]数据，和y相乘的列决定了当前列的位置，即为1
<br/>
之后一次类推；所有两个矩阵相乘需要确认[a,b][c,d] b=c 是否相等


In [39]:
# 关于矩阵乘法的Sample
# 如果都是2维，那么就是矩阵乘法的结果返回。与 torch.mm 是等价的，torch.mm 仅仅能处理的是矩阵乘法。

# numpy.dot() 对于两个一维的数组，计算的是这两个数组对应下标元素的乘积和(数学上称之为内积)；
# 对于二维数组，计算的是两个数组的矩阵乘积；对于多维数组，
# 它的通用计算公式如下，即结果数组中的每个元素都是：
# 数组a的最后一维上的所有元素与数组b的倒数第二位上的所有元素的乘积和： dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])。
import random
import torch

def matrix_multiple():
    
    x = torch.tensor([
        [1, 1, 1],
        [1, 1, 1]
    ])
    y = torch.tensor([
        [2, 2],
        [2, 2],
        [2, 3]
    ])
    # print(y.transpose(0,1))
    
    return torch.matmul(x, y), torch.mm(x, y)

print(matrix_multiple())
# (tensor([[6, 7],[6, 7]]), 
# tensor([[6, 7],[6, 7]]))

(tensor([[6, 7],
        [6, 7]]), tensor([[6, 7],
        [6, 7]]))
